package tribe.domain.enumaration;

public enum IdentityCategoryEnum {
	ATHLETIC, PRODUCTIVE, RELAX, EDUCATED, LEADER, CRAFTER,
	GOOD_PARTNER, ATTRACTIVE, SPIRITUAL, ECO_RESPONSIBLE, MINIMALIST,
	FINANCIALLY_INTELLIGENT
}
